/*
 * Fen_client.java
 *
 * Created on 13 janvier 2009, 10:22
 */

package chat_client;

import java.net.*;
import java.io.*;
import javax.swing.*;
import java.lang.*;

/**
 *
 * @author  rm188766
 */
public class Fen_client extends javax.swing.JFrame {
    
    private Socket Sock_principal;
    private Thread_client th_cli;
    private Liste_item_salon Liste_item_sal = new Liste_item_salon();
    private Client client;
    
    
    
    /** Creates new form Fen_client */
    public Fen_client() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        Message_salon_area = new javax.swing.JTextArea();
        Message_text = new javax.swing.JTextField();
        Envoyer_bout = new javax.swing.JButton();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Liste_salon = new javax.swing.JList();
        Connecter_salon_bout = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Nom_nouv_salon_text = new javax.swing.JTextField();
        Creer_nouv_salon_bout = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Ip_serveur_text = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Port_serveur_text = new javax.swing.JTextField();
        Connexion_serveur_bout = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        Reponse_serveur_area = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        Pseudonyme = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Message_salon_area.setColumns(20);
        Message_salon_area.setRows(5);
        jScrollPane2.setViewportView(Message_salon_area);

        jTabbedPane1.addTab("Nom salon", jScrollPane2);

        Envoyer_bout.setText("Envoyer"); // NOI18N
        Envoyer_bout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Envoyer_boutActionPerformed(evt);
            }
        });

        Liste_salon.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "eded", "ededeeeeeee" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(Liste_salon);

        Connecter_salon_bout.setText("Connecter à un salon"); // NOI18N
        Connecter_salon_bout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Connecter_salon_boutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Connecter_salon_bout, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Connecter_salon_bout))
        );

        jTabbedPane2.addTab("Salon", jPanel2);

        jLabel1.setText("Nom du salon :"); // NOI18N

        Creer_nouv_salon_bout.setText("Créer nouveau salon"); // NOI18N
        Creer_nouv_salon_bout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Creer_nouv_salon_boutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Nom_nouv_salon_text, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Creer_nouv_salon_bout))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Nom_nouv_salon_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Creer_nouv_salon_bout)
                .addContainerGap(316, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Nouveau", jPanel1);

        jLabel2.setText("IP Serveur :"); // NOI18N

        jLabel3.setText("Port Serveur :"); // NOI18N

        Connexion_serveur_bout.setText("Connexion au Serveur"); // NOI18N
        Connexion_serveur_bout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Connexion_serveur_boutActionPerformed(evt);
            }
        });

        Reponse_serveur_area.setColumns(20);
        Reponse_serveur_area.setRows(5);
        jScrollPane3.setViewportView(Reponse_serveur_area);

        jLabel4.setText("Pseudonyme :");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(Ip_serveur_text, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Port_serveur_text, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addContainerGap(156, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Pseudonyme, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                            .addComponent(Connexion_serveur_bout, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE))
                        .addGap(68, 68, 68))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Ip_serveur_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Port_serveur_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Pseudonyme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Connexion_serveur_bout)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        jTabbedPane2.addTab("Connexion", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Message_text, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Envoyer_bout, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Message_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Envoyer_bout)))
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void Envoyer_boutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Envoyer_boutActionPerformed

    Message_salon_area.setText(Message_salon_area.getText() + "\n" + Message_text.getText());
    
   
    
    
    
    
}//GEN-LAST:event_Envoyer_boutActionPerformed

private void Connexion_serveur_boutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Connexion_serveur_boutActionPerformed

    client = new Client(this.Pseudonyme.getText());
    
    Composant_Fen_client cfc = new Composant_Fen_client(this.Reponse_serveur_area, this.Liste_salon, this.Liste_item_sal);
    th_cli = new Thread_client(Ip_serveur_text.getText(), Integer.parseInt(Port_serveur_text.getText()), cfc, this.client);
    th_cli.start();
        
      

    
    
    
}//GEN-LAST:event_Connexion_serveur_boutActionPerformed


private void Connecter_salon_boutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Connecter_salon_boutActionPerformed

    
   
   
   //Reponse_serveur_area.setText(Liste_salon.getModel().getElementAt(1).toString());
   Liste_item_sal.addItem("id_client:" + String.valueOf(this.client.Get_id_client()));
   Liste_item_sal.addItem("pseudo:" + this.client.Get_pseudonyme());
   Liste_item_salon l = new Liste_item_salon();
   
   for(int i=0;i < Liste_item_sal.getSize();i++)
        l.addItem((String)Liste_item_sal.getElementAt(i));
      
  
   Liste_salon.setModel(l);
   
    
    
}//GEN-LAST:event_Connecter_salon_boutActionPerformed

private void Creer_nouv_salon_boutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Creer_nouv_salon_boutActionPerformed

       
    javax.swing.JScrollPane jScrollP1 = new javax.swing.JScrollPane();
    javax.swing.JTextArea Message_salon_area1 = new javax.swing.JTextArea();
   
    Message_salon_area1.setColumns(20);
    Message_salon_area1.setRows(5);
    jScrollP1.setViewportView(Message_salon_area1);

    jTabbedPane1.addTab(this.Nom_nouv_salon_text.getText(), jScrollP1);
    
    
}//GEN-LAST:event_Creer_nouv_salon_boutActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fen_client().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Connecter_salon_bout;
    private javax.swing.JButton Connexion_serveur_bout;
    private javax.swing.JButton Creer_nouv_salon_bout;
    private javax.swing.JButton Envoyer_bout;
    private javax.swing.JTextField Ip_serveur_text;
    private javax.swing.JList Liste_salon;
    private javax.swing.JTextArea Message_salon_area;
    private javax.swing.JTextField Message_text;
    private javax.swing.JTextField Nom_nouv_salon_text;
    private javax.swing.JTextField Port_serveur_text;
    private javax.swing.JTextField Pseudonyme;
    private javax.swing.JTextArea Reponse_serveur_area;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    // End of variables declaration//GEN-END:variables
  
}
